name: Publish Library

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.7

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            .venv
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('poetry.lock') }}-test

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: poetry install --no-dev --no-interaction

      - name: Set API Token
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: poetry config pypi-token.pypi ${PYPI_API_TOKEN}

      - name: Publish
        run: poetry publish --build
