name: Test

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - fastapi_cloud_logging/**/*.py
      - tests/**/*.py

jobs:
  test:
    name: "Testing library"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Lint
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./fastapi_cloud_logging"

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            .venv
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('poetry.lock') }}-test

      - name: Install Development Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: poetry install --no-interaction

      - name: Install Additional Development Dependencies
        if: steps.cache.outputs.cache-hit != 'true' && matrix.python-version == 3.7
        run: poetry install --no-interaction --extras "py37"

      - name: Test with pytest
        run: |
          poetry run pytest --junit-xml results/pytest.xml

      - name: Upload Unit Test Results
        uses: actions/upload-artifact@v3
        with:
          name: Unit Test Results (Python ${{ matrix.python-version }})
          path: results/*.xml

  publish-test-results:
    name: "Publish Unit Tests Results"
    needs: test
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "artifacts/**/*.xml"
